### ISSUE TITLE
[ENH] Add >MEMORY< and Thread Sanitizer support of GCC and CLang, more then ASAN

### ISSUE THREAD

**Issue by Kol9yN** [franneck94/Vscode-C-Cpp-Runner#100]
Any way to add icon in bottom ribbon for call sanitizer options as it did for choose working folder?

**Comment by franneck94** [comment]
I won't add more icons, there are already too much imo

**Comment by Kol9yN** [comment]
or add this option into settings, currently we have asan only, there my request about to add memory san, and thread san.

**Comment by franneck94** [comment]
I wont add this since its not implemented for all compilers.
I only want features that are avail. for all compiler

**Comment by Kol9yN** [comment]
Yeah i got it, same.
Here each compiler have own features for asan and memsan, maybe any way to make it auto pick depends of selected compiler(make "if" logic)?
