### ISSUE TITLE
Clean Command unclear 

### ISSUE THREAD

**Issue by HowsYourFather** [franneck94/Vscode-C-Cpp-Runner#106]
When I use "clean" the .exe file is deleted along with the .o files.

**Comment by franneck94** [comment]
Why should this be a bug?

**Comment by HowsYourFather** [comment]
Presumably one wishes to keep the .exe file because it is required for subsequent debugging whereas the object files are only temporary clutter having no use after the .exe has been created. Also, in your web page description, you mention only .o  files when explaining the "clean"  function.  I therefore assumed that the intention was to delete only the object files.

**Comment by franneck94** [comment]
> Also, in your web page description, you mention only .o files when explaining the "clean" function. 

 Okay sorry for that. Need to update the README then.
 Im not sure if i would update the code such that the exe is kept.

**Comment by HowsYourFather** [comment]
It's an insignificant flaw that can be easily circumvented by manually deleting the files as required. In fact, the delete button could be removed entirely and it wouldn't make any real difference. I raised the issue only because I thought it to be a minor slip-up that had crept in unnoticed. Best wishes.
