### ISSUE TITLE
Please help. 

### ISSUE THREAD

**Issue by niboon39** [franneck94/Vscode-C-Cpp-Runner#12]
![1](https://user-images.githubusercontent.com/30637687/125280820-b5f35500-e33f-11eb-930c-85a5638f7744.png)

**Comment by franneck94** [comment]
Hi, in MinGW the Makefile executable is called mingw32-make.exe.
Edit this in the local settings.json file.
Then it should work.

**Comment by niboon39** [comment]
Install mingw32-automake right?

**Comment by niboon39** [comment]
No error, but not working.
![image](https://user-images.githubusercontent.com/30637687/125288021-dfb07a00-e347-11eb-9549-f05902f22f0d.png)

**Comment by franneck94** [comment]
You forgot the ".exe" file extension

**Comment by niboon39** [comment]
I try. Not working.  😭

**Comment by franneck94** [comment]
Okay, could you try to move your project directly on C:/ and name the folder with english characters?

**Comment by franneck94** [comment]
I added a note to the README that the user should use english characters for the folder/file names.
