### ISSUE TITLE
[BUG] Can't build if path to folder has '&' in name

### ISSUE THREAD

**Issue by krysclarke** [franneck94/Vscode-C-Cpp-Runner#121]
As per the error in the screenshot attached.

![VSCodium cant build cpp](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/110656065/024b3589-014e-45f8-9fb8-338237f5b6c1)

My workaround has been to relocate the project folder to a part of the directory tree with a folder name that doesn't contain a '&'.

**Comment by franneck94** [comment]
As an Info: In unix shell '&' likewise as ' ' are special characters and should be avoided if possible.

**Comment by franneck94** [comment]
Note: This also fails with MSVC

**Comment by franneck94** [comment]
Note: Have not found a solution that works on all OS and compiler combinations.

**Comment by franneck94** [comment]
I will add this as a note in the README and will close this issue.
Just dont use whitespaces and special characters in filenames :)
