### ISSUE TITLE
Rename an Debug and Release output files

### ISSUE THREAD

**Issue by RavenGoku** [franneck94/Vscode-C-Cpp-Runner#122]
I have been trying to rename compilation output files, but couldn't find option for that.
Its always is either outDebug.exe or outRelease.exe.

May I ask how you can change that for folder name output? 
![Screenshot 2023-08-05 180248](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/52545907/92c32a62-fb7a-46ee-83ed-4ac38f04c037)

**Comment by franneck94** [comment]
Your can't
