### ISSUE TITLE
Please added the option to debug in the local terminal

### ISSUE THREAD

**Issue by wyh0106** [franneck94/Vscode-C-Cpp-Runner#128]
I've used some other code runners that don't open an extra shell when debugging, but instead open a session in a local terminal in vscode. Maybe I didn't find where this setting is, if really existing such a setting, please let me know, if such a setting does not exist, I would like to be able to add, thank you.

**Comment by franneck94** [comment]
Hi, can you send me a name of an extension with this behavior?

**Comment by franneck94** [comment]
Or do you mean the popup window with msvc as the Compiler?

**Comment by franneck94** [comment]
I highly discourage the behaviour of the Code Runner extension especially that the commands are not run in a "real" terminal, instead they use the output tab, right?
I dont like this at all tbh.

And no there is no such setting in my extension.
