### ISSUE TITLE
Not showing extension button on status bar neither works

### ISSUE THREAD

**Issue by draugvar** [franneck94/Vscode-C-Cpp-Runner#13]
When I open a folder with example c/cpp files there is no runner extension on my status bar to click on....
<img width="1720" alt="noRunner" src="https://user-images.githubusercontent.com/12036000/126866104-d6b42100-178d-46d9-842a-540b30b090ec.png">

**Comment by franneck94** [comment]
Hi, in your .vscode folder is there by any chance a Makefile file? This could explain this behaviour.

Does it work when you press `ctrl+alt+r.`?

**Comment by franneck94** [comment]
Could you also provide the following info:
OS, Compiler (also version) and Mak version.

**Comment by franneck94** [comment]
Hi, is it still an issue?

**Comment by draugvar** [comment]
Hey sry I was reading now. I will do the test asap thanks!
