### ISSUE TITLE
Debugger Path Setting Broken For VS Codium

### ISSUE THREAD

**Issue by DocLock17** [franneck94/Vscode-C-Cpp-Runner#143]
Using VSCodium on Linux Mint
Debugger Appears to be Path Setting Broken

Understanding clang must be set as selected compiler
![clangset](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/f577f2c4-e33b-49b6-81f7-4829e6284c11)

Found C_Cpp_Runner.debuggerPath Here:
![settingFound](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/e43d7a69-1f63-4664-928e-3514b24d0ce0)

Set it to LLDB as directed:
![corrected](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/e3123946-7c35-4615-a54c-c71a8b283f20)

Get this error when attempting to run:
![error](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/e977f7ec-7f02-487d-82af-77a942ff72bf)

I checked the settings.json file but didn't see any update to the file. So I manually updated too:
![manualset](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/68b14a9e-40fc-40b3-ae61-aef149bb8401)

Repeating my test I get the same error
![error](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/e977f7ec-7f02-487d-82af-77a942ff72bf)

Looking at launch.json I see:
![launchremains](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/f24de82b-b64d-46e2-aa5b-51f9b6a55d87)

By changing line 6 to 'lldb' this regains functionality:
![works](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/47020392/ea517a44-fbe4-4723-898b-943b2c200520)

However, this file is generated and gets overwritten so I seem to have to set this in the extension template itself. I made a YouTube video to show people how to do this until a better solution becomes available. NOTE: the error and apparent solution appear the same using 'gcc' as well.

**Comment by franneck94** [comment]
In the pictures above you changed the systems setting and not the local workspace settings

**Comment by DocLock17** [comment]
I included a picture of me manually setting the local workspace settings.json and it still isn't working though?

**Comment by franneck94** [comment]
But your right something went wront in the latest changes

**Comment by franneck94** [comment]
One question, are you using VScodium and not VSCode?

**Comment by DocLock17** [comment]
OH I thought I mentioned it earlier so I owe you a HUGE apology if I failed too. I am using VS Codium on Linux systems.

**Comment by DocLock17** [comment]
To be clear, is your extension not meant to be compatible with VS-Codium?

Perhaps I am just confused as to your target?

**Comment by franneck94** [comment]
It's only very partially compatible, since all of the Microsoft stuff is not available there

**Comment by DocLock17** [comment]
Completely understood. It was originally my hope to submit a simple solution and make your life easier. Now that I know it is not that simple, I will simply continue to use my workaround. 


I did prepare these two YouTube videos on setup with workarounds for Codium+Linux users.

# This one is for GCC users
https://www.youtube.com/watch?v=RkbZG6g83dE

# This one is for CLANG users
https://www.youtube.com/watch?v=Q8WZJ1qu6mg


You are certainly welcome to use these links or not as you see fit. I would love for them to be of use to you, but I expect nothing in particular. I really appreciate your extension, and I am grateful for your help and contribution! Thank you!

**Comment by DocLock17** [comment]
Hope this helps
