### ISSUE TITLE
[BUG] Apple ARM Selection in properties.json

### ISSUE THREAD

**Issue by franneck94** [franneck94/Vscode-C-Cpp-Runner#145]
Instead of arm, x64 is somehow selected

**Comment by franneck94** [comment]
Can appple arm user check if the c_cpp_properties will still select x64 instead of arm?

**Comment by GrossoLuca** [comment]
> Can apple arm user check if the c_cpp_properties will still select x64 instead of arm?

`{
  "configurations": [
    {
      "name": "macos-clang-arm64",
      "includePath": [
        "${workspaceFolder}/**"
      ],
      "compilerPath": "/usr/bin/clang",
      "cStandard": "${default}",
      "cppStandard": "${default}",
      "intelliSenseMode": "macos-clang-arm64",
      "compilerArgs": [
        ""
      ]
    }
  ],
  "version": 4
}`

this is what is what I have with Apple M1 chip

**Comment by GrossoLuca** [comment]
this is what I have on Mac M1 chip:

<img width="411" alt="Screenshot 2024-03-19 alle 13 13 26" src="https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/126894810/01f6a051-bbbf-4eb5-bca1-15ddc43713bc">

**Comment by franneck94** [comment]
Then it seems to be no issue anymore
