### ISSUE TITLE
.vscode folder without workspace settings

### ISSUE THREAD

**Issue by Terve16** [franneck94/Vscode-C-Cpp-Runner#148]
### .vscode folder without workspace settings

As soon as I open a .c file inside a workspace in VS Code, the .vscode folder is created altough I have not set any workspace settings. The files in the .vscode folder seem to belong to the Cpp runner extension.
In most cases I use VS Code as an editor only and I do not want to have the .vscode folder. So I have to delete it very often.
Can you please fix this or tell me how to change this behaviour?

**Comment by franneck94** [comment]
No, sorry i wont change this.
This is intended and needed behaviour of the extension
