### ISSUE TITLE
Step through

### ISSUE THREAD

**Issue by WildboyGG** [franneck94/Vscode-C-Cpp-Runner#150]
Hello! Problems encountered when downloading your warehouse code running: every time you run a single step debugging, run the activate function, still do not see the bottom left corner of several compiled run plug-in generation, may I ask why? Why run the generated.js project after running the Activate function at the same time? Could you answer that? Thank you very much

**Comment by franneck94** [comment]
I do not understand a single sentence. Why are you talking about JavaScript files?

**Comment by WildboyGG** [comment]
Sorry, I might not have described it well. After I single-step through the 'activate' function, the next single step jumps into the .js code, so I might be a bit confused, okay?

**Comment by WildboyGG** [comment]
I have a question, okay? Why does the icon in the bottom left corner only appear after the 'activate' function has finished running? When is the trigger for the bottom left icon activated?

**Comment by franneck94** [comment]
The activation conditions are defined here:

https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/bca9c8bcbc23e44344baee6d37c7334448153c62/package.json#L37C4-L37C20

**Comment by franneck94** [comment]
What do you want to debug in the extension?

**Comment by WildboyGG** [comment]
Yes, I'd like to extend the plugin with a cross-compilation feature, along with single-step debugging capability for microcontrollers.

**Comment by franneck94** [comment]
>  extend the plugin with a cross-compilation feature
 
 This should work out of the box isnt it?
