### ISSUE TITLE
[BUG] Extension constantly updates .vscode/settings.json

### ISSUE THREAD

**Issue by Gotoro** [franneck94/Vscode-C-Cpp-Runner#152]
https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/39387797/401176d8-c9e1-4790-90e4-0d75a17b802f

I have bare minimum of extensions enabled:
* C/C++
* C/C++ Runner
* CodeLLDB

I can't disable anything else as they depend on each other. When in a workspace, having .c file open creates 3 files in .vscode subdirectory: `c_cpp_properties.json`, `launch.json` and `settings.json`

I'm having problems with the `settings.json` file. Having it open (update: it doesn't matter if it's open or not) seemingly causes it to update all the time(see video), without letting me do any changes to it, while causing a lot of writes to the disk. Opening a new project does not fix the issue.
If you could provide the help to debug this further, that would be appreciated.

**Comment by Gotoro** [comment]
![image](https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/39387797/f508ee30-010c-444d-8c7c-1bea91084d2a)
It appears the issue is not new?

**Comment by Gotoro** [comment]
okay so in my case while loading the initial local settings in settingsProvider/ts? the msvcBatchPath is empty so it falls back to DEFAULT_MSVC_BATCH_PATH and tries to find the folder to msvc/ After failing to do so it updates the file with the empty value for msvcBatchPath/

**Comment by Gotoro** [comment]
okay so in my case while loading the initial local settings in settingsProvider.ts, the msvcBatchPath is empty so it falls back to DEFAULT_MSVC_BATCH_PATH and tries to find the folder to msvc. After failing to do so it updates the file with the empty value for msvcBatchPath.

Now the bug starts at the changeCallback function which gets called by the vscode watcher watching all files in .vscode/**. As the file was just changed now the function actually calls loadLocalSettings again, starting the infinite loop.

I'm not 100% sure if this is what's happening but that's what I got. I'll follow with a pr shortly

**Comment by franneck94** [comment]
Needs to be fixed by some other way

**Comment by franneck94** [comment]
To reproduce this, you dont have msvc installed right?

**Comment by Gotoro** [comment]
To add to this, even with the proposed fix, it seems a different issue occurs where an update to a config file causes the watcher to detect change multiple times (16 on a video). Maybe I'm misunderstanding something and it's supposed to work like that, but discovered this while testing. This doesn't cause any apparent problems as it seems, but maybe enough to open a different issue?

On video, changing launch.json somehow fires console.log multiple times:

https://github.com/franneck94/Vscode-C-Cpp-Runner/assets/39387797/04be6665-9fde-4a19-9f5e-110beea5b3e8

**Comment by franneck94** [comment]
Can you try the branch bug/infLoopMsvc'
Should be fixed there

**Comment by Gotoro** [comment]
Yes, the issue appears to be fixed with the mentioned commit. Thank you!
