### ISSUE TITLE
workspace's settings.json options are overwritten

### ISSUE THREAD

**Issue by ckkz-it** [franneck94/Vscode-C-Cpp-Runner#159]
I use code-server and have a predefined `settings.json` for the workspace. I set `"C_Cpp_Runner.debuggerPath": "lldb"` but it gets overwritten with defaults once I start the code-server. Is it possible to persist the initial value and provide defaults only for options that were not defined?

One note is that since it's the first time code-server is started, lldb binaries are fetched in the runtime (that's how `CodeLLDB` extension works) and are probably not there yet when your extension is initialized. The setting does persist if I change it manually after the initial start.

I run it in the devcontainer `linux 6.10.0-linuxkit arm64`. The extension is from the pack https://open-vsx.org/extension/franneck94/vscode-c-cpp-dev-extension-pack (the pack version is 0.10.0, and the extension version itself is 9.4.7).

**Comment by ckkz-it** [comment]
OK, so I've checked the code and found that you already support it but require all three [mandatory parameters to be set](https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/ba8462b7c44289c02197bda07485ec13974f6322/src/provider/settingsProvider.ts#L216L218) (`cCompilerPath`, `cppCompilerPath`, `debuggerPath`).

I see that you additionally validate if it exists using [fs.accessSync](https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/ba8462b7c44289c02197bda07485ec13974f6322/src/utils/fileUtils.ts#L32) but the issue with it is it doesn't work with binaries on the path, like `gcc` or `g++`, you have to specify the full path in the settings (i.e. `/usr/local/bin/gcc`).

Also, with `lldb` it's slightly different because as mentioned in the original comment it's fetched dynamically by the extension so it doesn't exist by the time you initialize settings (at least in my setup). To workaround this I had to do `touch /usr/local/bin/lldb` so the `fs.accessSync` check passes.

In the end, I have a working solution with this setup:

```json
{
  "C_Cpp_Runner.cCompilerPath": "/usr/local/bin/gcc",
  "C_Cpp_Runner.cppCompilerPath": "/usr/local/bin/g++",
  "C_Cpp_Runner.debuggerPath": "/usr/local/bin/lldb"
}
```

I would like to contribute but would like to hear your input first.

**Comment by franneck94** [comment]
The settings can also just have the commands name instead of a full path.
So "GCC" should also work.

**Comment by ckkz-it** [comment]
> So "GCC" should also work.

I've tested and it didn't work. Since `fs.accessSync` failed the extension assumed that I do not have such a file and used default values. Example, if you have this:

```json
{
  "C_Cpp_Runner.cCompilerPath": "gcc",
  "C_Cpp_Runner.cppCompilerPath": "/usr/local/bin/g++",
  "C_Cpp_Runner.debuggerPath": "/usr/local/bin/lldb"
}
```

it will be turned into

```json
{
  "C_Cpp_Runner.cCompilerPath": "gcc",
  "C_Cpp_Runner.cppCompilerPath": "g++",
  "C_Cpp_Runner.debuggerPath": "gdb"
}

**Comment by franneck94** [comment]
> > So "GCC" should also work.
> 
> I've tested and it didn't work. Since `fs.accessSync` failed the extension assumed that I do not have such a file and used default values. Example, if you have this:
> 
> ```json
> {
>   "C_Cpp_Runner.cCompilerPath": "gcc",
>   "C_Cpp_Runner.cppCompilerPath": "/usr/local/bin/g++",
>   "C_Cpp_Runner.debuggerPath": "/usr/local/bin/lldb"
> }
> ```
> 
> it will be turned into
> 
> ```json
> {
>   "C_Cpp_Runner.cCompilerPath": "gcc",
>   "C_Cpp_Runner.cppCompilerPath": "g++",
>   "C_Cpp_Runner.debuggerPath": "gdb"
> }
> ```

Dont you mean the lower is transformed in to the upper?

**Comment by franneck94** [comment]
![image](https://github.com/user-attachments/assets/a52ae85f-b47e-4c6f-bf34-75c0af248477)

Thats what i mean. I only check if the path exits, if its an absolute path

**Comment by ckkz-it** [comment]
I believe it won't even get to these lines of code. [Here's the check](https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/ba8462b7c44289c02197bda07485ec13974f6322/src/provider/settingsProvider.ts#L216L218) that will fail with just `gcc` or `g++` (it doesn't do any `isNonRelativePath` checks). It will result in a [settingsMissing](https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/ba8462b7c44289c02197bda07485ec13974f6322/src/provider/settingsProvider.ts#L157) to be `true` which will [force to overwrite local (workspace) settings](https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/ba8462b7c44289c02197bda07485ec13974f6322/src/provider/settingsProvider.ts#L166) by global ones (or default ones if there are no global). That's what I experienced when was testing.

**Comment by ckkz-it** [comment]
> Dont you mean the lower is transformed in to the upper?

No, the upper is transformed into the lower. I don't have any global settings, just workspace settings.

**Comment by ckkz-it** [comment]
Here's what it looks like.

I'm changing it in my workspace `.vscode/settings.json` file:

![image](https://github.com/user-attachments/assets/f8d5e0b4-315e-418d-b696-eb646f1bc381)

then I start a code-server instance and open this settings file:

![image](https://github.com/user-attachments/assets/9f931981-ca1c-4f53-830a-8029f5ff804f)

the settings got overwritten

If I change `gcc` to `/usr/local/bin/gcc` - it will work (since `fs.accessSync` will also now return `true` for the full `gcc` path).

**Comment by franneck94** [comment]
So if localSettingExist will also check for the program on PATH in addition to checking if its an abs path, it would work for you?

**Comment by ckkz-it** [comment]
Yeah, that would be perfect. Check if it's accessible via the terminal since that's how it will be accessed later.
