### ISSUE TITLE
It doesn't download for online version 

### ISSUE THREAD

**Issue by Program4christ** [franneck94/Vscode-C-Cpp-Runner#160]
It doesn't download for online version

**Comment by Program4christ** [comment]
I mean the vs code.dev
    On Tuesday, September 3, 2024 at 03:28:27 PM GMT+1, Jan Schaffranek ***@***.***> wrote:  
 
 


Sorry I don't know what you mean. What online version?

**Comment by franneck94** [comment]
It wont work anyway since no compiler is installed there

**Comment by Program4christ** [comment]
Thanks 
    On Wednesday, September 11, 2024 at 08:15:57 AM GMT+1, Jan Schaffranek ***@***.***> wrote:  
 
 


It wont work anyway since no compiler is installed there
