### ISSUE TITLE
The "args" property in launch.json assigns null to file pointer

### ISSUE THREAD

**Issue by katiyaya** [franneck94/Vscode-C-Cpp-Runner#164]
Type: <b>Bug</b>

1. Arguments are passed to the desired target, the program executes, passes the needed number of arguments (argc) check, but assigns NULL to file pointer when trying to open the file passed as an argument.
The program is executes normally without any issues on bash with the provided command line argument.
2. Application executes normally in bash via ./Application testcases/singlefailure.conf command

Platform and versions:
Operating System: Ubuntu
VSCode Version: 1.94.0 
Compiler/Toolchain: GCC 11.4.0
C/C++ Runner v 9.4.9

Launch.json
`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C/C++ Runner: Debug Session",
      "type": "cppdbg",
      "request": "launch",
      "args": [
        "testcases/singlefailure.conf"
      ],
      "stopAtEntry": false,
      "externalConsole": false,
      "cwd": "/home/katiyabrk/my-gossip-protocol/testcases",
      "program": "/home/katiyabrk/my-gossip-protocol/Application",
      "MIMode": "gdb",
      "miDebuggerPath": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}`
P.S. I had problems with passing the arguments when the argc wasn't correct, as i.ve searched it was an issue https://github.com/microsoft/vscode-cmake-tools/issues/1594, but i managed it by installing the C/C++ runner which seems to accept the arguments but the file pointer is assigned NULL. Could this be related to the issue described in the link above?

Extension version: 9.4.9
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2891)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.04GB free)|
|Process Argv|--crash-reporter-id 3d34cbf7-87ca-46ed-bc7b-891051e30360|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 0)|
|Memory (System)|3.78GB (2.40GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by franneck94** [comment]
Can you print out the argv values to the console? I just want to see what's inside the argv

**Comment by katiyaya** [comment]
![Screenshot (15)](https://github.com/user-attachments/assets/d0147f7d-6198-469e-be0c-536ada498c40)

**Comment by katiyaya** [comment]
![Screenshot (20)](https://github.com/user-attachments/assets/4748a122-cdbc-4a00-af54-43a4cdbae3e7)

**Comment by franneck94** [comment]
Sorry I meant the full content of argv, that's just the first character.

**Comment by franneck94** [comment]
You should get it by 

argv[1],20

In the debug console

**Comment by katiyaya** [comment]
![Screenshot (22)](https://github.com/user-attachments/assets/e8113a11-32e5-4250-a526-04721e649281)
Hope that's correct

**Comment by franneck94** [comment]
Yes thanks.
So it seems that the path to the file is correct, isnt it?
So its rather an issue with you code.
For example you are using relative paths that do not match instead of absolute paths.
