### ISSUE TITLE
broken setting in vscode (C_Cpp > Default: Compile Commands)

### ISSUE THREAD

**Issue by albmef** [franneck94/Vscode-C-Cpp-Runner#165]
Hi 
where to we set the compile_commands.json path for zephyr project ?

i try to follow the document below but the C_Cpp > Default: Compile Commands setting is no longer available
https://docs.zephyrproject.org/latest/develop/tools/vscode.html

please help

thanks
bob

**Comment by franneck94** [comment]
I dont know what zephyr is, but at first glance it seems that there is a cmake project used, is this correct?

**Comment by albmef** [comment]
Hi
https://www.zephyrproject.org/
i'ts a FOSS, RTOS OS that runs on ressource limited targets like microcontrollers.
its build system (west) uses cmake
i'm a noob with VSCODE and CMAKE, what i'm trying to do is follow the tutorial and allow VSCODE to build a zephyr project. But since the vscode C/C++ extension broke its setting names i'm not able to proceed with how to configure the compile_commands.json path.
bob

**Comment by albmef** [comment]
it seems related to something called "intellisense"
https://code.visualstudio.com/docs/cpp/faq-cpp

bob

**Comment by albmef** [comment]
ok i minstakenly installed the wrong vscode extension
the one i needed is the official C/C++ extension provided by microsoft but curiously it did not appeared in the marketplace as it was replaced by the c/c++ extension pack that uses a similar name and icon, hence the mistake...
here is the one i need in zephyr https://code.visualstudio.com/docs/languages/cpp
