### ISSUE TITLE
Script fails to prevent folders with ' and " in the name from messing with the script 

### ISSUE THREAD

**Issue by fluoriteByte** [franneck94/Vscode-C-Cpp-Runner#169]
i sometimes need to use project with an ```'``` in the name, this messes up with the script that this extension uses

Log: ```
*  Executing task: /bin/sh -c gcc -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference -g3 -O0 -c /home/illy/Documents/CompileStuff/L'algorithmique/chapitre_01.c -o ./build/Debug/chapitre_01.o && gcc -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference -g3 -O0  -c /home/illy/Documents/CompileStuff/L'algorithmique/chapitre_02.c -o ./build/Debug/chapitre_02.o && gcc -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference -g3 -O0  -c /home/illy/Documents/CompileStuff/L'algorithmique/chapitre_02_Tableaux.c -o ./build/Debug/chapitre_02_Tableaux.o && gcc -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference -g3 -O0   ./build/Debug/chapitre_01.o ./build/Debug/chapitre_02.o ./build/Debug/chapitre_02_Tableaux.o -o ./build/Debug/outDebug 

/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
```

**Comment by franneck94** [comment]
I dont think i can fix this in an easy way.
