### ISSUE TITLE
Can’t compile with space in path

### ISSUE THREAD

**Issue by Thomas-Cassar** [franneck94/Vscode-C-Cpp-Runner#17]
After selecting a folder and hitting the build button the make command fails when there is spaces in the path. EX: “Executing task: usr/bin/make build —directory=/home/user/My Project With Space”

**Comment by franneck94** [comment]
Hi, this is the expected behaviour. [See](https://github.com/franneck94/Vscode-C-Cpp-Runner#important-notes)
