### ISSUE TITLE
Hope to add an option to close the extension's auto start-up.

### ISSUE THREAD

**Issue by XIVN1987** [franneck94/Vscode-C-Cpp-Runner#20]
Sometimes I open a directory just to read and study someone else's code.
Do not want C/C++ Runner to modify the configuration file.
If need using it, i can activate it manually.

**Comment by franneck94** [comment]
For the moment the easiest way would be to deactivate the extension per default and only activate it for certain workspaces.

**Comment by XIVN1987** [comment]
Yeah, this a good method.
Thanks very much.
