### ISSUE TITLE
Make doesn't compile anything

### ISSUE THREAD

**Issue by afkfish** [franneck94/Vscode-C-Cpp-Runner#23]
Hi im new to this but i'm having an issue and after serious research i still lost. I'm on windows and installed mingw as welll as all the other things that is needed, changed the settings so the gcc and g++.exe is in the correct location and the make.exe as well but when i want to compile a pretty basic c program it always generates an empty folder and leaves no error that i could recognise and solve.
As i said i'm pretty noob in this.
![image](https://user-images.githubusercontent.com/63806903/133684295-51c0afcf-a246-4195-838e-04648e75c7fe.png)
![image](https://user-images.githubusercontent.com/63806903/133684492-45d39897-6a53-4e10-a165-3a04d909ba79.png)

**Comment by franneck94** [comment]
Based on your screenshots i do not see if the build directory is empty or not.
Could you provide a screenshot?

And what behaviour did you expect on the second screenshot?

**Comment by afkfish** [comment]
![image](https://user-images.githubusercontent.com/63806903/133819636-7dcc9377-1e5d-4828-a3c9-c28ee30901ed.png)
![image](https://user-images.githubusercontent.com/63806903/133819639-9f2af23f-9337-44aa-b403-7cfaaed3d16c.png)
 that it will build the program, the second screenshot was just a retry wether if it would magically be good but it just doesnt do anything after it generated the folders

**Comment by franneck94** [comment]
Inside the build folder there is the debug folder a d there is the executable. But you can just click on the play button in the blue status bar. Everything works as expected for you

**Comment by afkfish** [comment]
there is no such file 
![image](https://user-images.githubusercontent.com/63806903/133823595-d7fbeb54-867d-42f6-959d-fcbdc5a20389.png)
and no errorr as well
![image](https://user-images.githubusercontent.com/63806903/133823647-4c197afe-4b03-4ff3-8118-454749b5f2ff.png)

**Comment by afkfish** [comment]
https://files.fm/u/gfh368jxf#/view/jmy3rcam8

**Comment by franneck94** [comment]
Okay, very interasting.
Currently i cannot image what the problem might be.

Could you try this with a different make/compiler setup (if you have installed something else than msys/mingw64)

**Comment by afkfish** [comment]
im currently installing cygwin

**Comment by afkfish** [comment]
i dont know what is the issue but still with cygwin as well its just bad
![image](https://user-images.githubusercontent.com/63806903/133830058-db71a488-c99f-4cd0-ad46-c435045b0c17.png)

**Comment by afkfish** [comment]
Its probably fixed but i dont think it is the best solution, so i tried everything and so i ran the command what the vscode is using when generating the file in a command promt and that generated the files successfully. The generate button still doesnt work it does not change or modify the exe and the run does not start the program but at least i can generate the file manually.
I dont know wether this is an issue with the compiler or smt else but from vscode its still bad.
If i can provide anything to further investigate what could be the issue please ask.

**Comment by franneck94** [comment]
What is the output of this command in the CMD when you are in the current workspace dir?

```
tree /F
```

I dont know if it is maybe a permission problem on your PC with creating the exe.

**Comment by afkfish** [comment]
![image](https://user-images.githubusercontent.com/63806903/133849868-c733e76c-29c9-4f78-8595-2aa2d61d794d.png)
its the same as in the vs code terminal but here it is working
i guess i could be but i dont see why it cant build a file on my desktop

**Comment by franneck94** [comment]
Can you try to start VSCode as admin and then retry?

**Comment by afkfish** [comment]
It did the same, nothing changed still the directories are the only things that are being created.

**Comment by franneck94** [comment]
Do you have by any chance WSL installed on your windows pc?
If so, you could try it on the WSL.

I still have the feeling that the issue has something to do with user permissons.

**Comment by afkfish** [comment]
No I don't have that.

**Comment by franneck94** [comment]
Can you try to use the experimental setting (after setting this VSCode restart is needed).
This should work then.

**Comment by franneck94** [comment]
I will add a fix that for MinGW Users, Makefile is not used anymore but instead the currently called "experimental setting" is used.

**Comment by afkfish** [comment]
it makes a different errorr but its something
![image](https://user-images.githubusercontent.com/63806903/133883530-0334c0db-3d24-4747-be08-123028bcdf2f.png)

**Comment by franneck94** [comment]
PowerShell really sucks again.
I will try to add a fix for the PowerShell.

**Comment by afkfish** [comment]
thank you for all i really apreaciate and i will wait then for the fix, and thank you for your patience

**Comment by franneck94** [comment]
The issue with PowerShell will be fixed in todays release 1.4.0.
For the MinGW problem i still dont have a solution.

**Comment by afkfish** [comment]
The experimental thing fixed it so the only issue was the power shell. The new version works well thank you!
