### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by diegorego75** [franneck94/Vscode-C-Cpp-Runner#25]
- Issue Type: `Performance`
- Extension Name: `c-cpp-runner`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\diego\AppData\Local\Temp\franneck94.c-cpp-runner-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by franneck94** [comment]
Currently the extension should be fast enough on start-up. However, since the compilers are searched on the PC it can take some milliseconds.
