### ISSUE TITLE
How do I change the "type" default inside launch.json?

### ISSUE THREAD

**Issue by psudo-dev** [franneck94/Vscode-C-Cpp-Runner#27]
I'm running C but the launch.json settings for C/C++ Runner always defaults to:
`"type": "cppdbg"`

but I need it to be:
`"type": "lldb"`

I already have:
`"C_Cpp_Runner.cCompilerPath": "/usr/bin/clang"`
`"C_Cpp_Runner.debuggerPath": "/usr/bin/lldb"`

Is it possible to change the default to `"lldb"` or do I always have to change it manually?

Thanks!

**Comment by franneck94** [comment]
The type is correct, see [here](https://code.visualstudio.com/docs/cpp/config-clang-mac#_debug-helloworldcpp).
For using lldb you only have to set the entries **MIMode** and **MIPath**.

**Comment by psudo-dev** [comment]
but if I put:
`"type": "cppdbg"`

I get this message:
```json
lldb: unrecognized option `--interpreter=mi'
error: unknown or ambiguous option
```

and if put `"type": "lldb"` it runs normally.  
Isn't `"type": "cppdbg"` for C++?

Thanks

**Comment by psudo-dev** [comment]
but if I put:
`"type": "cppdbg"`

I get this message:

```json
lldb: unrecognized option `--interpreter=mi'
error: unknown or ambiguous option
```

and if put `"type": "lldb"` it runs normally.
Isn't `"type": "cppdbg"` for C++?

Thanks

**Comment by franneck94** [comment]
C/C++ are handled with the same tools and extensions by Microsoft in VSCode.
So the type is correct for both.
If you have an error with the launch.json file, you might open an issue in Microsofts C/C++ extension, since i just stick to their guide.

**Comment by psudo-dev** [comment]
I see, well, I just wanted to know if there was a way to customize it, if there is not, no problem.

I'm a Mac user. That's the full message already. Is there a way to get a more complete log?

**Comment by franneck94** [comment]
So currently the content of the launch file is auto-generated by this extension and will be updated after selecting a new active folder.

For logging the debugger see [here](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
