### ISSUE TITLE
[ENH] Use `c_Cpp.default.includePath` instead of `c_cpp_runner.include_paths?

### ISSUE THREAD

**Issue by erwin** [franneck94/Vscode-C-Cpp-Runner#29]
After I installed the C/C++ Runner extension, I was surprised to see that many of my include paths were no longer found.

I had set the include paths that I want in my default `~/.config/Code/User/settings.json` under `C_Cpp.default.includePath`.

If the value hasn't been explicitly set in C_Cpp Runner, perhaps you can read the `C_Cpp.default.includePath` as a fallback for people that don't want to duplicate the same list of paths in two places?

**Comment by franneck94** [comment]
Hi, as a note.
The current state of the extension at least reads in the includePath from the local .vscode/c_cpp_properties.json file whenever you open an C/C++ project where you havn't initialized this extension yet.
