### ISSUE TITLE
math.h link in makefile und runner 

### ISSUE THREAD

**Issue by Avdar-IIW** [franneck94/Vscode-C-Cpp-Runner#39]
Hi Jan,

ich hab den math.h implementiert, der Programm wollte aber nicht kompilieren, nach etwas Suche sah ich, dass der -lm Option fehlte. Hab ihn dann in deiner (von C kurs) Makefile wie unten hinzufügt.

#############
#############

build_single:
	$(COMPILER_CALL) -o $(EXECUTABLE_NAME) $(FILE_NAME) -lm

ich weiß es aber nicht wie man das beim Runner auch hinzufügt.

**Comment by franneck94** [comment]
Hi,

with the setting "C_Cpp_Runner.linkerArgs" you can set the linker arguments.
For more information see extension settings entry of the [README](https://github.com/franneck94/Vscode-C-Cpp-Runner/blob/master/README.md#extension-settings).
