### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sollo11** [franneck94/Vscode-C-Cpp-Runner#4]
- Issue Type: `Performance`
- Extension Name: `c-cpp-runner`
- Extension Version: `0.12.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Neuro\AppData\Local\Temp\franneck94.c-cpp-runner-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by franneck94** [comment]
Hi, i am not familiar with the cpuprofile workflow.
So, you measured a high cpu load for this extension, or do you assume that there is a high cpu load?
