### ISSUE TITLE
Shortcut to compile multiple files

### ISSUE THREAD

**Issue by FayardProf** [franneck94/Vscode-C-Cpp-Runner#46]
Hi,

Is there a shortcut to compile multiple files in the directory. I can do that with the icons at the bottom of the screen, but I can't find a keyboard shortcut to do such a thing.

Thanks for your plugin which is very helpful and works as expected.

Francois

**Comment by franneck94** [comment]
Hi, no there is no shortcut.
But if you dont like to use your mouse you could open the command palette and run the Build command there ;)

![image](https://user-images.githubusercontent.com/20141069/145374819-82847bb2-0604-4b15-a7ce-7abc97902a5b.png)

**Comment by FayardProf** [comment]
Thanks. I've manager to configure it.
