### ISSUE TITLE
How can I run Valgrind memory check via this extesnion?

### ISSUE THREAD

**Issue by wojsiu** [franneck94/Vscode-C-Cpp-Runner#5]
I use C/C++ Runner it mostly because I don't have to do makefile by my own, however i would like to use linker to do a memory check.

**Comment by franneck94** [comment]
So you dont run valgrind like this?
![image](https://user-images.githubusercontent.com/20141069/120642902-c4fc0300-c475-11eb-984e-07d58974091d.png)

You want to link valgrind while compiling?

**Comment by wojsiu** [comment]
Thank you very much for this solution, I did't know that "outDebug" is extension-outside usable file.
Wish you all the best!
