### ISSUE TITLE
Using the MSVC compiler

### ISSUE THREAD

**Issue by FayardProf** [franneck94/Vscode-C-Cpp-Runner#50]
Hi,

I need some help to use C/C++ Runner with MSVC. I have set up

"C_Cpp_Runner.msvcBatchPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

in my settings file for VS Code (AppData/Roaming/Code/User/settings.json), but C/C++ Runner still wants to find gcc. It says :

[1/9/2022, 3:37:04 PM] Unable to resolve configuration with compilerPath "gcc".  Using "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64\cl.exe" instead.

But when I try to compile, it tries to install gcc which is not available. What's wrong with my setup?

Thanks for your help.
Francois

**Comment by franneck94** [comment]
Hi, all settings must be set in the local .vscode folder of your workspace

**Comment by FayardProf** [comment]
Thanks. It works now.

But when I open an empty folder, it automatically creates a new .vscode file and I have to manually set the C_Cpp_Runner.msvcBatchPath in the settings.json file. Is there a way so that the settings.json file generated already contains the right setting ?

Francois

**Comment by franneck94** [comment]
Currently no.

**Comment by FayardProf** [comment]
Ok. Thanks for your help. As a feature request, it would be nice to have the same for the Intel oneAPI compiler which is free.

Thanks for your project,
Francois
