### ISSUE TITLE
Error in C debugging

### ISSUE THREAD

**Issue by programonauta** [franneck94/Vscode-C-Cpp-Runner#53]
Hi,

I've just installed VS Codium, but when I try to debug any C program, I get this error:

![image](https://user-images.githubusercontent.com/6033539/150649899-ba7fc2b2-90d4-469c-84da-e1c666ff6e17.png)

I'm using Debian 11, gdb and gcc with versions:

```
$ gdb --version
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Is it missing any other extension? The following extensions is already installed:

- [C/C++ Config[(https://open-vsx.org/extension/ms-vscode/cmake-tools)
- [CMake](https://open-vsx.org/extension/twxs/cmake)
- [CMake Tools](https://open-vsx.org/extension/ms-vscode/cmake-tools)

**Comment by franneck94** [comment]
Debugging is then not possible in vscodium, since this extension needs the Microsoft's C++ extension for the full feature plate.

**Comment by programonauta** [comment]
> Debugging is then not possible in vscodium, since this extension needs the Microsoft's C++ extension for the full feature plate.
> 
> However compiling and running should work.

Thanks for information @franneck94
