### ISSUE TITLE
Extension's still not working on latest vscode version

### ISSUE THREAD

**Issue by Javiooli** [franneck94/Vscode-C-Cpp-Runner#60]
I have just updated the extension to 3.2.0 and the empty "> Executing task:" doesn't happen anymore.
However, now every time I try to build (via ctrl+alt+B) I receive an Invalid argument error message because apparently "outDebug.exe" cannot be opened.

![image](https://user-images.githubusercontent.com/95071210/156881868-24e85cb9-015b-4165-b490-bb0f3e91ebad.png)

**Comment by franneck94** [comment]
Does your workspace path contain whitespace?

**Comment by Javiooli** [comment]
Yes, it had whitespaces. I have removed them and now it works fine. What seems weird to me is my workspace has been the same for weeks (with whitespaces in the folders' names) and I haven't run into this issue until today...

**Comment by franneck94** [comment]
Since the new vscode version 1.65 i had to change the code.

**Comment by franneck94** [comment]
Should work again in 3.2.1.
However, i am not able to get debugging working atm if there are whitespaces in the path.
