### ISSUE TITLE
It would be nice to be able to modify the command line for the compiler

### ISSUE THREAD

**Issue by Reneg973** [franneck94/Vscode-C-Cpp-Runner#66]
E.g. Seems like it is not possible to modify -O3. Would be nice feature!

**Comment by franneck94** [comment]
Hi, you could just enter the optimization flag in the "compilerArgs" field, the standard one should be overwritten.
https://godbolt.org/z/obeqbrdYv

**Comment by Reneg973** [comment]
I tried the compilerArgs already, what happened in command line was the following:
clang++ ... -O3 ... -O1
It compiled without errors but I think the second parameter was simply ignored

**Comment by franneck94** [comment]
At least in the Compiler Explorer link, the first argument is overridden.

**Comment by Reneg973** [comment]
Ok thanks, seems to work. Now the only issue is that the same command line parameters are applied to debug and release.
