### ISSUE TITLE
Vscode Settings for Runner don't work

### ISSUE THREAD

**Issue by GeekBar-Boss** [franneck94/Vscode-C-Cpp-Runner#72]
Hey Franneck, I hope I didn't bother!
I want to add gcc args "-fexec-charset" and "-mwindows"  as a default setting in the .vscode auto-generated by C/C++ Runner.
But I found it not working to set Compiler Args and Warnings of C/C++ Runner in Settings of Vscode.
I don't know if it's a bug or the way I configured it was wrong.
And here are the imgs of my configurations:
![image](https://user-images.githubusercontent.com/19168163/163700385-694f1426-e77f-454c-868a-557e557f118c.png)
![image](https://user-images.githubusercontent.com/19168163/163700449-3b182d78-834e-4620-9d1d-2abb536b8413.png)

**Comment by franneck94** [comment]
You must edit the local .vscode/settings.json file and not the user settings

**Comment by GeekBar-Boss** [comment]
Thanks for your attention! 
So I request for the functionality of editing default configuration which could be loaded to generate local .vscode files if possible. 
Thank you for providing such a convenient extension to the c/c++ programmers with vscode.

**Comment by franneck94** [comment]
Should be fixed in 4.0.0
