### ISSUE TITLE
adding include folders render the build command not working 

### ISSUE THREAD

**Issue by ajmandourah** [franneck94/Vscode-C-Cpp-Runner#73]
Hello, 

I am trying to use MSVC  but when Include folders the build command will not work 

'C:\Program' is not recognized as an internal or external command,

would you look at that please, 

![image](https://user-images.githubusercontent.com/27051374/166557790-e4d44938-ce54-4e86-903b-9678f56abf95.png)

**Comment by franneck94** [comment]
Can you send a screenshot of the full console output?

**Comment by ajmandourah** [comment]
here you go 
![image](https://user-images.githubusercontent.com/27051374/166627345-de8ba5ab-c817-439c-b780-e7a89f8a0eb3.png)

.

**Comment by franneck94** [comment]
Okay whenever there is more than one include dir added the error occurs. I am working on it.

**Comment by ajmandourah** [comment]
Any options to use an external terminal?

While at it, I noticed that options for setting vcvarsall.bat and include folders won't setup automatically in new projects rathat than I must set it in manually in user settings or in settings json file. Would be great if such would be automated. Especially for include folders.

**Comment by ajmandourah** [comment]
So I managed to find a workaround for now, its pretty dirty and messy but works well. Mainly using the windows file names shortcut which is still being used in the background, for example Program Files will translate to progra~1.
when set like that I must change all the dir in the command line to the shortcut version including path to vsvarsall , include folders  and such. 

you can find what the folder name will translate to using "dir /x" in the folder and it will list its name and the shortcut name,

**Comment by ajmandourah** [comment]
the whole line will look sth like this

`"C:\progra~1\MIB055~1\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 && cl.exe /W4 /Od /Zi /EHsc /IC:\progra~1\MIB055~1\2022\Community\VC\Tools\MSVC\14.31.31103\include\ /IC:\progra~2\WI3CF2~1\10\Include\10.0.19041.0\um /DYNAMICBASE kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib -DUNICODE /Fd.\build\Debug\ /Fo.\build\Debug\ /Fe.\build\Debug\outDebug.exe  Source.cpp`

**Comment by franneck94** [comment]
**Wasn't** able to fix this in 4.0.0

**Comment by franneck94** [comment]
#76
