### ISSUE TITLE
multi cpp don't work

### ISSUE THREAD

**Issue by jinduoxia** [franneck94/Vscode-C-Cpp-Runner#75]
Hello Franneck.
I want to write the implementation of the function in another .cpp file, but it doesn't work. The file structure is as follows:
- workspaceFolder
    -  include
        - function.h
    - src
        - function.cpp
    - main.cpp
the error is "undefined reference to" the xxx, when xxx is implemented in function.cpp.

However it can work when I change the file structure as follows:
- workspaceFolder
    -  include
        - function.h
    - main.cpp
    - function.cpp

I know the reason is that function.cpp is not included and compiled when it is in the include folder. How can I solve this problem?
THanks!

**Comment by franneck94** [comment]
You cannot solve this with this extension. All source files must be in the same directory.
