### ISSUE TITLE
Runner not working with $(default)-Loop

### ISSUE THREAD

**Issue by die-horschis** [franneck94/Vscode-C-Cpp-Runner#77]
Hi Jan,

i activated your runner-tool with clean setup, your extension pack and the newest git. And your CPP Udemy Course.

After selecting a directory and click on the debug button, the tool produced a 

"$(default)"
 
loop in settings and also one "$(default)" in the cpp-properties-file:

{
  "configurations": [
    {
      "name": "windows-cygwin-gcc-x64",
      "includePath": [
        "${workspaceFolder}/**",
        "$(default)"
      ],
      "compilerPath": "C:/cygwin64/bin/gcc.exe",
      "cStandard": "${default}",
      "cppStandard": "${default}",
      "intelliSenseMode": "linux-gcc-x64",
      "compilerArgs": [
        ""
      ]
    }
  ],
  "version": 4
}

I tried to overwrite it with ${default}, but it doesn't work. The settings.json still hangs in a loop, adding more and more lines of this:

"C_Cpp_Runner.includePaths": [
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",
    "$(default)",

Did I something wrong? Additional info: The Visual Studio Community Edition is installed on the same system.

Best regards

Michael

**Comment by franneck94** [comment]
Do you have this $(default) defined somewhere?
I do not know where this is coming from

**Comment by die-horschis** [comment]
Hi Jan,

Ich glaube, wir können auf Deutsch kommunizieren. Ich habe keine Ahnung, wo das herkommt.

Habe zunächst das .vscode-Verzeichnis gelöscht, dann VS Code neu installiert, dann Deine komplette Extension, dann den Runner aktiviert und das neueste CPP-Repository geklont (neueste GIT-Version Windows) und dann versucht, das erste Beispiel zu kompilieren. Vorher habe ich das passende Solution-Verzeichnis ausgewählt.

Dann kommt sofort der Fehler. Und in der Settings.json werden jede Menge Defaulteinträge produziert, während ich versuche, diese zu löschen.

Ohne die Runner-Extension kann ich normal kompilieren.

Und: Ganz lieben Dank für die ultraschnelle Antwort, ganz toll.

Wenn Du möchtest, kann ich Dir noch Versionsnummern etc. schicken.

Ich versuche jetzt mal, das Ganze in einer VM nachzuvollziehen.

Beste Grüße 

Michael Horsch

Von meinem iPhone gesendet

**Comment by franneck94** [comment]
Is this still a problem in 4.0.2?

**Comment by die-horschis** [comment]
Hi Jan,

no problems with Ubuntu 20.04 LTS, but GIT is not installed. 

Best regards 

Michael

**Comment by franneck94** [comment]
Have you set the global setting for the include path?

**Comment by die-horschis** [comment]
This works for me, thanks! There was an entry in c_cpp Default: Include Path, but i have no idea, who or which extension had inserted it. 

Thanks a lot for your excellent support.
