### ISSUE TITLE
splitting sorce folder

### ISSUE THREAD

**Issue by lknaeble** [franneck94/Vscode-C-Cpp-Runner#78]
hi
is there a possibility to split the src and header folder?
withe google proto I got a lots of *.cc and *.h files which I would like to put insight a "proto" folder. (so "myProgramm/src/proto" and "myProgramm/header/proto") 

It would make my folders so match more structured

Cheers
lknaeble

**Comment by franneck94** [comment]
More complex use-cases should be handeled by CMake projects.
