### ISSUE TITLE
[ENH] Show compiler warnings in warnings tab

### ISSUE THREAD

**Issue by fronders** [franneck94/Vscode-C-Cpp-Runner#79]
Hi! Is there a way to parse compiler output and show it in problems list? Also the task output doesn't show if the build was successfull or not

**Comment by franneck94** [comment]
Since the vscode update in july the errors does not show up anymore.
I have to check how to display them again and how to see the compiler output

**Comment by franneck94** [comment]
"Also the task output doesn't show if the build was successfull or not"

This only applied if the task is "re-run" in an prev. opened task tab.
So currently you havbe to close the task tab after one compilation step.
Then a new task tab will be opened and you should see the compiler command and output again,

**Comment by fronders** [comment]
No it doesn't. Even if the task is run first time, I don't see anything like `Build successful, errors: 0, warnings: 0` or `Build failed, errors: 1, warnings: 3`. This forces to read through all the compiler log and see if there was error or not - very inconvenient

Here's a screenshot of first build after selecting the folder:
![image](https://user-images.githubusercontent.com/15352046/193532291-bec93863-dc7e-41e4-beac-67d448a1281c.png)

And even if it did solve the problem - closing the build task window every time is a PITA solution tbh, can't you just output a text message log as the last line?

**Comment by franneck94** [comment]
Ah okay i thought u meant something else.
Yes, there is currently no list of how many warnings.
However, if there is an error in build the returned result from the task will be non zero.

**Comment by fronders** [comment]
Yes, I but how would I see the returned result of the build task if I start the build using the bottom toolbar button? :)

**Comment by franneck94** [comment]
![image](https://user-images.githubusercontent.com/20141069/193611398-63a261e1-35db-4790-a3f8-d2f26391ef5b.png)

**Comment by franneck94** [comment]
Warnings are again displayed in the "problems" tab
