### ISSUE TITLE
Workspace settings get initialized by global defaults rather than User values

### ISSUE THREAD

**Issue by lahwaacz** [franneck94/Vscode-C-Cpp-Runner#82]
When I change e.g. `C_Cpp_Runner.cCompilerPath` on the _User_ tab to `clang` and delete the current `settings.json` in the `.vscode` directory, the setting gets initialized to `/usr/bin/gcc` when the `.vscode/settings.json` file is recreated.

**Comment by lahwaacz** [comment]
Also I'd appreciate if the extension created `.vscode/settings.json` only when some setting gets changed. Otherwise the settings are needlessly duplicated and the _default_ values have no meaning because essentially every project/directory gets its own settings file.

**Comment by franneck94** [comment]
Isnt it like every project will have a settings file anyway?
I wont change that this file is created. However, as you said, the global setting should be used as default value

**Comment by franneck94** [comment]
So your bug report is the following:

1.) You already opened a project and the settigns file is created.
2.) Afterwards, you updated the global setting for the compiler path
3.) Deleting the local .vscode/settings file will not take the globally updated setting?

**Comment by franneck94** [comment]
This would work as expected, because if only the settings file is removed, the compiler path from the c_cpp_properties file is taken instead of the global setting.
So if you update the global setting you should close the current project, delete the whole .vscode folder and then reopen it.
