### ISSUE TITLE
Can't build or run single file

### ISSUE THREAD

**Issue by MC-dusk** [franneck94/Vscode-C-Cpp-Runner#85]
> How to use: Compile a single file
> 1️⃣ Open the C/C++ file you want to compile (build).
> 2️⃣ Select either debug or release mode for building the binary (debug is the default case).
> 3️⃣ To build the binary press ctrl+alt+b.
> 4️⃣ To run the binary press ctrl+alt+r.
> 5️⃣ To debug the binary press ctrl+alt+d.

Those three hotkeys don't work for me. Just nothing happened after pressing.

**Comment by franneck94** [comment]
Which operating system?
Please provide a screenshot of the workspace you have opened

**Comment by MC-dusk** [comment]
win10 22H2
![image](https://user-images.githubusercontent.com/52311860/204705818-b92db923-498a-45f4-b699-57c9665a11d8.png)

**Comment by franneck94** [comment]
Please add a screenshot of the full VSCode window

**Comment by MC-dusk** [comment]
![image](https://user-images.githubusercontent.com/52311860/204780562-8d461e24-d85d-4510-bc57-b177be28a6f6.png)
![image](https://user-images.githubusercontent.com/52311860/204780747-c2f2aa22-08ce-4053-8949-ac93b1859d17.png)

**Comment by MC-dusk** [comment]
Well, I have deleted previous response posted 10min before because I've found what the problem is.
If there is only one c/c++ file in the folder, then everything goes well.
If you need more info, please tell me and I'll post more. Thank you.

**Comment by franneck94** [comment]
ctrl+alt+b.
Should also work if there are multiple files in the same dir, thats the idea behidn that keyboard shortcut

**Comment by MC-dusk** [comment]
To be more precisely, if there are c and cpp files in the same folder, and try to compile c file, the `ctrl+alt+b` will be invalid. But `ctrl+b` is fine and it will only compile cpp file.

---

![image](https://user-images.githubusercontent.com/52311860/205242614-a9f45249-66e4-4ce5-a32e-b885fc535398.png)
![image](https://user-images.githubusercontent.com/52311860/205242308-42d1bbb0-d8ab-4179-901b-85c28a895d95.png)
![image](https://user-images.githubusercontent.com/52311860/205242427-4077d23f-1c44-40a5-a43f-17c2c559f238.png)
![image](https://user-images.githubusercontent.com/52311860/205242474-423c79ea-89d7-4bba-a377-2d504157711c.png)

**Comment by franneck94** [comment]
You cannot have a c++ program without a main that's the issue on that screenshot regardless of the extension

**Comment by MC-dusk** [comment]
That's just an example, not meaning that I want to compile an empty cpp file. I want to show you that even the cpp file is all commented, the c file can't be compiled. The second picture I added a cpp file and I can't use hotkey then.

**Comment by franneck94** [comment]
Okay regarding Pic 2 i never testes having C and C++ files in the same dir

**Comment by franneck94** [comment]
Fixed in 4.3.1
