### ISSUE TITLE
Cannot install from marketplace

### ISSUE THREAD

**Issue by UMP-Dan** [franneck94/Vscode-C-Cpp-Runner#88]
Not sure if vscode issue or not, but when I go to install this from the vs code marketplace, cpu gets pegged to max and freezes the marketplace.  all other installs are fine

**Comment by franneck94** [comment]
Is this still an issue?

**Comment by UMP-Dan** [comment]
Yeah still can’t get it

Cheers,
Daniel

On 16 Dec 2022, at 7:41 pm, Jan Schaffranek ***@***.***> wrote:

﻿

Is this still an issue?

**Comment by franneck94** [comment]
What do you mean with marketplace?

This: https://marketplace.visualstudio.com/vscode ?
So You downloaded the vsix file?
