### ISSUE TITLE
Code Runner

### ISSUE THREAD

**Issue by Rajkamalyadav707** [franneck94/Vscode-C-Cpp-Runner#9]
Code runner in unable to run the code of C/C++ sometime .
And it's showing as an error for some inbuilt function as well .
Due to bug in the extension there is lot's of words are moving here and there due to which it cause an problem with the code running time we unable to find the output of the console .

**Comment by Rajkamalyadav707** [comment]
Code runner in unable to run the code of C/C++ sometime .
And it's showing as an error for some inbuilt function as well .
Due to bug in the extension there is lot's of words are moving here and there due to which it cause an problem with the code running time we unable to find the output of the console .

**Comment by franneck94** [comment]
Can you provide an example code and a screenshot of the full error message?
