### ISSUE TITLE
[ENH]: Add ability to change task terminal

### ISSUE THREAD

**Issue by Kol9yN** [franneck94/Vscode-C-Cpp-Runner#90]
Currently by default it uses cmd on win10.
I want to set it to Bash or Power Shell for example, in VSCode settings i change it to Bash as default, but your extension still run compiler and tasks in cmd. Thats not good.
Thanks for your attention. Hope it will be fixed asap.

**Comment by franneck94** [comment]
Can you give me an example where this would be needed?

**Comment by Kol9yN** [comment]
after compile project and lunch exe/
I think need to add some setting to choose type of terminal, or link it to current default terminal in VSC settings.

**Comment by franneck94** [comment]
> after compile project and lunch exe

You cant reuse the terminal instance that executes or compiles, so i dont see a point there

**Comment by franneck94** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/20141069/209399668-7c3b822f-af6c-46ab-8c2a-e58c77c630ad.png">

So what does the Git Bash or Pwershell change there?

**Comment by Kol9yN** [comment]
i not mean to reuse, i mean replace or change cmd.exe to bash.exe

**Comment by Kol9yN** [comment]
Reasons why:
Make it colorized :)
Show more info about compile (how many time was spent to comlipe, etc)

**Comment by Kol9yN** [comment]
Thank you sooo much to accept my ticket :)
Cant wait to try new feature :)

**Comment by franneck94** [comment]
Currently, it is not planned.
Especially PowerShell would makes a lot of problems.

**Comment by Kol9yN** [comment]
Skip PowerShell? :) ;)

**Comment by franneck94** [comment]
I have decided that i will not implement this.
