### ISSUE TITLE
[Feature]: Add panel button or option in settings for sanitize memory after build

### ISSUE THREAD

**Issue by Kol9yN** [franneck94/Vscode-C-Cpp-Runner#92]
Use "-fsanitize=address -g" its supports by GCC (G++) by default.

You can read more about it here:
https://stackoverflow.com/questions/37970758/how-to-use-addresssanitizer-with-gcc

https://stackoverflow.com/questions/64636821/how-to-stop-using-addresssanitizer

Its Windows analog of Valgrind but builtin in GCC

? Show results in current terminal or Outup of VSC

? Another variant for Win its "Dr. Memory" tool, maybe any way to implement it into your extension?

**Comment by franneck94** [comment]
Windows GCC and MSVC also have the memory sanitizer, no need for Dr Memory.

But in general good feature request.

**Comment by franneck94** [comment]
Implemented in #97

**Comment by Kol9yN** [comment]
Thank you so much for implementation, but how to use it correctly?
