### ISSUE TITLE
[ENH] Сreate an option to modify the encoding.

### ISSUE THREAD

**Issue by 123kapefa** [franneck94/Vscode-C-Cpp-Runner#93]
"code-runner.executorMap": [ 
"C++": "set C++IOENCODING=utf8 && py -u" 
]

**Comment by franneck94** [comment]
Hi, can you give me an use-case?

Shouldnt the OS terminal have UTF8?

**Comment by 123kapefa** [comment]
thanks. I’ve already solved this problem

пт, 17 февр. 2023 г. в 10:23, Jan Schaffranek ***@***.***>:
