### ISSUE TITLE
[Feature]: Use Error and Warning Status Bar Items instead of hard coded value 

### ISSUE THREAD

**Issue by staatzstreich** [franneck94/Vscode-C-Cpp-Runner#96]
Hey :)

Because I am using a light color schema where statusbar background color is light gray, the "Select Folder" in yellow Text is hard to see...

Maybe you can change this to an Error or Warning Statusbar Item instead as described here:
https://code.visualstudio.com/api/ux-guidelines/status-bar

I am sorry but I have never investigated to do Extension - Development.. so I could not help with a PR for now.

Best,
Michael

**Comment by franneck94** [comment]
Fixed in #97
