### ISSUE TITLE
[Critical bug] Memory sanitizier ASAN dont work on Win 10\11 and broke compilation process

### ISSUE THREAD

**Issue by Kol9yN** [franneck94/Vscode-C-Cpp-Runner#98]
Bug going same if i turn off "Use Address Sanitizer" in settings...

:( :( :(

https://stackoverflow.com/questions/55018627/cannot-find-lasan-using-address-sanitizer-in-qt-creator-in-windows-mingw

C:/Windows/System32/cmd.exe /d /c g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wconversion -Wnull-dereference -Wsign-conversion -fsanitize=address --std=c++23 -g3 -O0 -c d:\test\CPP_Code\demo\src\main.cpp -o .\build\Debug\main.o && g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wconversion -Wnull-dereference -Wsign-conversion -fsanitize=address --std=c++23 -g3 -O0 .\build\Debug\main.o -o .\build\Debug\outDebug.exe 

d:/soft/cppcompiler/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan: No such file or directory
collect2.exe: error: ld returned 1 exit status

**Comment by franneck94** [comment]
Does your compiler support this?
If not, then it abviously wont compile

**Comment by Kol9yN** [comment]
![sanTurnOn](https://user-images.githubusercontent.com/10098740/220184922-6cbfc073-44a3-4d50-826a-c48da8ba59c1.png)
its automatically turns ON when im uncheck it :)

**Comment by franneck94** [comment]
Is this the local or user setting?

**Comment by franneck94** [comment]
You have to edit the local settings.json and not the workspace settings tab.

**Comment by Kol9yN** [comment]
doing same

**Comment by franneck94** [comment]
Can you record a video or a gif for that behavior?

**Comment by Kol9yN** [comment]
after change manually in json file, it holds ok

**Comment by franneck94** [comment]
The extension always relies on editing the local file, or you could set the global settings. 

But the workspace settings like in your screenshot do not send an eventListener event to the extension.

**Comment by Kol9yN** [comment]
probably, how to check and fix it?
