### ISSUE TITLE
[ENH] Unable to Compile Large Projects

### ISSUE THREAD

**Issue by NicDz** [franneck94/Vscode-C-Cpp-Runner#99]
## Unable to Compile Large Projects ##

I've got a project with 350 files (about 170 .c files). When running the debug build, I receive the following error:

> "The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 206)."

Is it possible to change a setting to compile one file at a time?

**Comment by franneck94** [comment]
ctrl + alt + b
For compiling only one file.

**Comment by NicDz** [comment]
Yes, this shortcut works for one file. But how to compile all the files into one executable?

**Comment by NicDz** [comment]
Correct, one main function.

**Comment by franneck94** [comment]
Then just click the gear icon in the blue status bar

**Comment by NicDz** [comment]
I get this error message, "The command line is too long."

**Comment by franneck94** [comment]
Yes beacuse of that many files. And no there is no workaround with this extension

**Comment by NicDz** [comment]
Alright, I guess I'll use a CMake

**Comment by Kol9yN** [comment]
Maybe any way to call CMake with arguments or auto create CMakeLists file and other CMake envelope for solve it?

**Comment by NicDz** [comment]
@franneck94, have you considered compiling with *.c instead of listing every file name + path?

**Comment by franneck94** [comment]
I don't think that the compilers can handle this

**Comment by franneck94** [comment]
I can add this when there are more than 10 files in a dir.
Otherwise i will keep the existing logic.
